// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:recruitment_app/models/users_group/users_group.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    int? id,
    required String firstName,
    required String lastName,
    required String birthDate,
    required String address,
    required List<UsersGroup> joinedGroupsList,
  }) = _User;

  factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
}
